author: Dendrobyte
version: 3.4
api-version: 1.14
name: OneInTheChamber
main: com.oitc.dendrobyte.Main
description: A custom OITC plugin!
softdepend: [Multiverse-Core]
commands:
  oitc:
    usage: /<command>
    description: General use of the oitc command
permissions:
  oitc.admin:
    description: Allows admin commands to be used
